seafoodservice/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _


import settings

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^captcha/', include('captcha.urls')),
)

#pages
urlpatterns += patterns('pages.views',
    url(r'^$', 'main', name='home'),
)

#services
urlpatterns += patterns('services.views',
    url(r'^services/$', 'services', name='services'),
)

#contacts
urlpatterns += patterns('contacts.views',
    url(r'^contacts/$', 'contacts', name='contacts'),
)

#news
urlpatterns += patterns('information.views',
    url(r'^news/$', 'news', name='news'),
    url(r'^news/(?P<news_id>\d+)/$', 'news_item', name='news_item'),
    url(r'^useful-information/$', 'useful_information', name='usefull_information'),
    url(r'^useful-information/(?P<information_id>\d+)/$', 'useful_information_item', name='usefull_information_item'),
)

#gallery
urlpatterns += patterns('gallery.views',
    url(r'^gallery/$', 'gallery', name='gallery'),
    url(r'^get_slide_images/$', 'get_slide_images', name='get_slide_images'),
)

#certificates
urlpatterns += patterns('certificates.views',
    url(r'^certificates/$', 'certificates', name='certificates'),
)

contacts/models.py
# coding: utf-8
from django.utils.translation import ugettext_lazy as _
from django.db import models
from mptt.models import MPTTModel

class Contact(MPTTModel):
    parent = models.ForeignKey('self', null=True, blank=True, related_name="related")

class OfficeContact(Contact):
    address = models.CharField(max_length=255, verbose_name=_("Address"))

    def __unicode__(self):
        return u'%s' % (self.address)

    class Meta:
        verbose_name = _(u"Office Contact")
        verbose_name_plural = _(u"Office Contacts")



class Employee(Contact):
    first_name = models.CharField(max_length=255, blank=False, null=False, verbose_name=_("First name"))
    last_name = models.CharField(max_length=255, verbose_name=_("Last name"))
    second_name = models.CharField(max_length=255, verbose_name=_("Second name"))
    post = models.CharField(max_length=255, verbose_name=_("Post"))

    def __unicode__(self):
        return u'%s - %s %s %s' % (self.first_name, self.second_name, self.last_name, self.post)

    class Meta:
        verbose_name = _(u"Employee")
        verbose_name_plural = _(u"Employees")



class TelephoneNumber(models.Model):
    contact = models.ForeignKey(Contact)
    number = models.CharField(max_length=255, verbose_name=_("Number"))

    def __unicode__(self):
        return u'%s' % (self.number)

    class Meta:
        verbose_name = _(u"TelephoneNumber")
        verbose_name_plural = _(u"TelephoneNumbers")


class Email(models.Model):
    contact = models.ForeignKey(Contact)
    email = models.CharField(max_length=255, verbose_name=_("Email"))

    def __unicode__(self):
        return u'%s' % (self.email)

    class Meta:
        verbose_name = _(u"Email")
        verbose_name_plural = _(u"Emails")

class SkypeName(models.Model):
    contact = models.ForeignKey(Contact)
    skype_name = models.CharField(verbose_name=_("Skype"), max_length=255)

    def __unicode__(self):
        return u'%s' % (self.skype_name)

    class Meta:
        verbose_name = _(u"Skype")
        verbose_name_plural = _(u"Skype records")



class FaxNumber(models.Model):
    contact = models.ForeignKey(Contact)
    fax_number = models.CharField(verbose_name=_("Fax"), max_length=255)

    def __unicode__(self):
        return u'%s' % (self.fax_number)

    class Meta:
        verbose_name = _(u"Fax")
        verbose_name_plural = _(u"Fax numbers")


class Message(models.Model):
    name = models.CharField(max_length=255, verbose_name=_(u"Your name"))
    number = models.CharField(max_length=255, verbose_name=_(u"Contact number"), null=True, blank=True)
    email = models.EmailField(verbose_name=_(u"Email"))
    message = models.TextField(verbose_name=_(u"Your message"))


    class Meta:
        verbose_name = _(u"User message")
        verbose_name_plural = _(u"User messages")

contacts/forms.py
from django import forms
from captcha.fields import CaptchaField
from django.utils.translation import ugettext_lazy as _

from models import Message


class LeaveMessageForm(forms.ModelForm):
    captcha = CaptchaField(label=_("Letters from picture"),
                           output_format='%(text_field)s %(image)s %(hidden_field)s')

    class Meta:
        model = Message
    prefix = "leave_message"

contacts/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.views.generic.edit import CreateView
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url
from django.http import HttpResponse
import json
from django.utils.translation import ugettext_lazy as _

from models import *
from information.views import set_required_data
from forms import LeaveMessageForm

def contacts(request):
    context = {}
    if request.POST:
        form = LeaveMessageForm(request.POST)
        print form
        if form.is_valid():
            form.save()
            context['notifications_messages']=[_(u"Thank you, we received your message.")]
            form = LeaveMessageForm()
        else:
            context['notifications_messages']=[_(u"Form is not valid!\nPlease correct your errors bellow.")]
    else:
        form = LeaveMessageForm()
    context['form'] = form
    context.update(dict(contacts=[{
                                 "contact": employee,
                                 "skypes": SkypeName.objects.filter(contact=employee),
                                 "numbers": TelephoneNumber.objects.filter(contact=employee),
                                 "emails": Email.objects.filter(contact=employee)}
                                for employee in Employee.objects.all()],
                   office_contacts=[dict(contact=office, skypes=SkypeName.objects.filter(contact=office),
                                         numbers=TelephoneNumber.objects.filter(contact=office),
                                         emails=Email.objects.filter(contact=office),
                                         faxs=FaxNumber.objects.filter(contact=office))
                                    for office in OfficeContact.objects.all()])
    )
    context.update(set_required_data(request))

    return render_to_response('contacts.html',
                          context,
                          context_instance=RequestContext(request))

contacts/templates/contacts.html
{% extends 'new_base.html' %}
{% load i18n admin_tools_menu_tags %}

{% block head %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/jquery.contacts.css">
    <script src="{{ MEDIA_URL }}js/jquery.maskedinput.js" type="text/javascript"></script>
{% endblock %}

{% block page %}
    {% block breadcrumbs %}
        <ul class="breadcrumbs">
            <li><a href="{% url 'home' %}">{% trans "Home" %}</a></li>
            <li>{% trans "Contacts" %}</li>
        </ul>
    {% endblock %}


    {% if contacts %}
    <article>
        <h3 class="useful_information">{% trans "Our employees" %}</h3>
    </article>
        {% for contact in contacts %}
            <div class="contacts_block">
                <p class="post">{{ contact.contact.post }}</p>

                <p class="name">{{ contact.contact.full_name }}</p>

                <div class="contact_info">
                    {% if contact.numbers %}
                        <img src="{{ MEDIA_URL }}css/images/phone.png"
                             alt="">
                        {% for number in contact.numbers %}
                            <p>{{ number }}</p>
                        {% endfor %}
                    {% endif %}

                    {% if contact.emails %}
                        <img src="{{ MEDIA_URL }}css/images/mail.png"
                             alt="">
                        {% for mail in contact.emails %}
                            <a href="mailto:{{ mail }}"><p>{{ mail }}</p>
                            </a>
                        {% endfor %}
                    {% endif %}

                    {% if contact.skypes %}
                        <img src="{{ MEDIA_URL }}css/images/skype.png"
                             alt="">
                        {% for skype in contact.skypes %}
                            <a href="skype:{{ skype }}"><p>{{ skype }}</p>
                            </a>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="cls"></div>

    {% endif %}


    {% if office_contacts %}
    <article>
        <h3 class="useful_information">{% trans "Office Contacts" %}</h3>
    </article>
        <div class="ofices_contacts">
            {% for contact in office_contacts %}
                <p>{{ contact.contact.address }}</p>
                <div class="office_info">
                    {% if contact.numbers %}
                        <p>
                        <img src="{{ MEDIA_URL }}css/images/phone.png"
                             alt="">

                        {% for number in contact.numbers %}
                            <a>{{ number }}</a>
                        {% endfor %}
                    </p>
                    {% endif %}
                    {% if contact.emails %}
                        <p>
                        <img src="{{ MEDIA_URL }}css/images/mail.png"
                             alt="">

                        {% for mail in contact.emails %}
                            <a href="mailto:{{ mail }}">{{ mail }}</a>
                        {% endfor %}
                    </p>
                    {% endif %}
                    {% if contact.skypes %}
                        <p>
                        <img src="{{ MEDIA_URL }}css/images/skype.png"
                             alt="">
                        {% for skype in contact.skypes %}
                            <a href="skype:{{ skype }}">{{ skype }}</a>
                        {% endfor %}
                    </p>
                    {% endif %}
                    {% if contact.faxs %}
                        <p>
                        <img src="{{ MEDIA_URL }}css/images/fax.png"
                             alt="">
                        {% for number in contact.numbers %}
                            {{ number }}
                        {% endfor %}
                    </p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

    {% endif %}

    <article>
        <h3 class="coord">{% trans "Our coordinates" %}</h3>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9396.550337768962!2d27.5420675!3d53.9292995!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dbc57e5ec3ebf3%3A0x5abc3d60c090ea35!2z0J3QvtCy0L7QstC40LvQtdC90YHQutCw0Y8g0YPQuy4gOCwg0JzQuNC90YHQuiwg0JHQtdC70LDRgNGD0YHRjA!5e0!3m2!1sru!2s!4v1412673455688"
                width="794" height="378" frameborder="0"
                style="margin-left:8px"></iframe>
    </article>

    <article>
        <h3 class="message">{% trans "Please, leave a message" %}</h3>

        <form action="" id="sendMessageForm" method='POST'>{% csrf_token %}
            {% if form.errors %}
                <p class="error_leave_message_label">
                    {% for error in form.errors %}
                        {{ error }}<br/>
                    {% endfor %}
                </p>
            {% endif %}

            {% for field in form %}
                <div>
                    <label for="id_{{ field.name }}">{{ field.label }} {% if field.field.required %}*{% endif %}</label>
                    {% if field.name == 'number' %}
                        <input id="id_{{ field.name }}"  type="text" placeholder="+XXX XX XXX XX XX" name="{{ field.name }}"/>
                    {% else %}
                        {{ field }}
                    {% endif %}
                    {% if field.name == 'captcha' %}<div class="cls"></div>{% endif %}
                </div>
            {% endfor %}
            <p class="required">{% trans "Fields marked as * are required" %}</p>
            <div>
                <input type="submit" value="{% trans "Submit" %}"
                       class="input_button"/>

                <input type="reset" class="cancel" value="{% trans "Cancel" %}">
                <div class="cls"></div>
            </div>
        </form>
    <script>
        jQuery(function($){
           $("#id_number").mask("[+](999) 99 999 99 99");
        });
    </script>
    </article>
{% endblock %}
	